
export const ADDING_SHIPMENT_SUCCESS = 'ADDING_SHIPMENT_SUCCESS';
export const ADDING_SHIPMENT_FAILED = 'ADDING_SHIPMENT_FAILED';
export const ADDING_SHIPMENT = 'ADDING_SHIPMENT';

export const SIGNUP_ATTEMPT = 'SIGNUP_ATTEMPT';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

export const LOGIN_ATTEMPT = 'LOGIN_ATTEMPT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';


export const LOADING_SHIPMENT = 'LOADING_SHIPMENT';
export const LOADING_SHIPMENT_SUCCESS = 'LOADING_SHIPMENT_SUCCESS';
export const LOADING_SHIPMENT_FAILED = 'LOADING_SHIPMENT_FAILED';

export const LOADING_MATHCING_SHIPMENT = 'LOADING_MATHCING_SHIPMENT';
export const LOADING_MATCHING_SHIPMENT_SUCCESS = 'LOADING_MATCHING_SHIPMENT_SUCCESS';
export const LOADING_MATCHING_SHIPMENT_FAILED = 'LOADING_MATCHING_SHIPMENT_FAILED';

export const PROFILE_FAILED   = 'profile_failed';
export const PROFILE_SUCCESS  = 'profile_success';
export const EDIT_PROFILE     = 'edit_profile';

export const LOADING_PROFILE          = 'loading_profile';
export const LOADING_PROFILE_SUCCESS  = 'loading_profile_success';
export const LOADING_PROFILE_FAILED   = 'loading_profile_failed';

export const PASSWORD_FAILED   = 'password_failed';
export const PASSWORD_SUCCESS  = 'password_success';
export const EDIT_PASSWORD     = 'edit_password';

export const FORGET_PASSWORD_FAILED   = 'forget_password_failed';
export const FORGET_PASSWORD_SUCCESS  = 'forger_password_success';
export const SEND_EMAIL    = 'send_email';

export const LOADING_COUNTRIES = 'LOADING_COUNTRIES';
export const LOADING_COUNTRIES_SUCCESS = 'LOADING_COUNTRIES_SUCCESS';
export const LOADING_COUNTRIES_FAILED = 'LOADING_COUNTRIES_FAILED';


export const LOADING_CATEGORIES = 'LOADING_CATEGORIES';
export const LOADING_CATEGORIES_SUCCESS = 'LOADING_CATEGORIES_SUCCESS';
export const LOADING_CATEGORIES_FAILED = 'LOADING_CATEGORIES_FAILED';

export const LOADING_OFFERS = 'LOADING_OFFERS';
export const LOADING_OFFERS_SUCCESS = 'LOADING_OFFERS_SUCCESS';
export const LOADING_OFFERS_FAILED = 'LOADING_OFFERS_FAILED';

export const MESSAGE_RECIEVED = 'MESSAGE_RECIEVED';
export const FETCHING = 'FETCHING';
export const ADDING_CHAT = 'ADDING_CHAT';

export const ADDING_OFFER= 'ADDING_OFFER';
export const ADDING_OFFER_SUCCESS= 'ADDING_OFFER_SUCCESS';
export const ADDING_OFFER_FAILED= 'ADDING_OFFER_FAILED';



export const CANCEL_OFFER   = 'CANCEL_OFFER';
export const CANCEL_OFFER_SUCCESS  = 'CANCEL_OFFER_SUCCESS';
export const CANCEL_OFFER_FAILED  = 'CANCEL_OFFER_FAILED';

export const LOADING_DEAL   = 'LOADING_DEAL';
export const LOADING_DEAL_SUCCESS  = 'LOADING_DEAL_SUCCESS';
export const LOADING_DEAL_FAILED  = 'LOADING_DEAL_FAILED';

export const ADDING_PHOTO   = 'ADDING_PHOTO';
export const PHOTO_SUCCESS  = 'PHOTO_SUCCESS';
export const PHOTO_FAILED  = 'PHOTO_FAILED';

export const VERIFY_CODE   = 'VERIFY_CODE';
export const VERIFY_CODE_SUCCESS  = 'VERIFY_CODE_SUCCESS';
export const VERIFY_CODE_FAILED  = 'VERIFY_CODE_FAILED';

export const SEND_PHONE   = 'SEND_PHONE';
export const SEND_PHONE_SUCCESS  = 'SEND_PHONE_SUCCESS';
export const SEND_PHONE_FAILED  = 'SEND_PHONE_FAILED';

export const EDITING_TRIP_FAILED   = 'EDITING_TRIP_FAILED';
export const EDITING_TRIP  = 'EDITING_TRIP';
export const EDITING_TRIP_SUCCESS  = 'EDITING_TRIP_SUCCESS';

export const ADDING_TRIP = 'ADDING_TRIP';
export const ADDING_TRIP_SUCCESS = 'ADDING_TRIP_SUCCESS';
export const ADDING_TRIP_FAILED = 'ADDING_TRIP_FAILED';

export const LOADING_TRIP = 'LOADING_TRIP';
export const LOADING_TRIP_FAILED = 'LOADING_TRIP_FAILED';
export const LOADING_TRIP_SUCCESS = 'LOADING_TRIP_SUCCESS';


export const DELETE_TRIP  = 'DELETE_TRIP';
export const DELETE_TRIP_FAILED  = 'DELETE_TRIP_FAILED';
export const DELETE_TRIP_SUCCESS  = 'DELETE_TRIP_SUCCESS';

export const EDITING_SHIPMENT_FAILED   = 'EDITING_SHIPMENT_FAILED';
export const EDITING_SHIPMENT  = 'EDITING_SHIPMENT';
export const EDITING_SHIPMENT_SUCCESS  = 'EDITING_SHIPMENT_SUCCESS';

export const DELETE_SHIPMENT  = 'DELETE_SHIPMENT';
export const DELETE_SHIPMENT_FAILED  = 'DELETE_SHIPMENT_FAILED';
export const DELETE_SHIPMENT_SUCCESS  = 'DELETE_SHIPMENT_SUCCESS';



export const VERIFY_EMAIL  = 'VERIFY_EMAIL';
export const VERIFY_EMAIL_SUCCESS  = 'VERIFY_EMAIL_SUCCESS';
export const VERIFY_EMAIL_FAILED  = 'VERIFY_EMAIL_FAILED';

export const RATING_FAILED  = 'RATING_FAILED';
export const RATING_SUCCESS  = 'RATING_SUCCESS';
export const RATING_USER  = 'RATING_USER';

export const LOADING_RATING_FAILED  = 'LOADING_RATING_FAILED';
export const LOADING_RATING_SUCCESS  = 'LOADING_RATING_SUCCESS';
export const LOADING_RATING  = 'LOADING_RATING';


export const LOADING_RATING_RECEIVED_FAILED  = 'LOADING_RATING_RECEIVED_FAILED';
export const LOADING_RATING_RECEIVED_SUCCESS  = 'LOADING_RATING_RECEIVED_SUCCESS';
export const LOADING_RECEIVED_RATING  = 'LOADING_RECEIVED_RATING';

export const LOADING_RATING_GIVEN_FAILED  = 'LOADING_RATING_GIVEN_FAILED';
export const LOADING_RATING_GIVEN_SUCCESS  = 'LOADING_RATING_GIVEN_SUCCESS';
export const LOADING_GIVEN_RATING  = 'LOADING_GIVEN_RATING';


export const SEND_FAILED  = 'SEND_FAILED';
export const SEND_MESSAGE  = 'SEND_MESSAGE';
export const SEND_SUCCESS  = 'SEND_SUCCESS';


export const LOADING_MESSAGES_SUCCESS  = 'LOADING_MESSAGES_SUCCESS';
export const LOADING_MESSAGES  = 'LOADING_MESSAGES';
export const LOADING_MESSAGES_FAILED  = 'LOADING_MESSAGES_FAILED';

export const LOADING_USER_MESSAGES_SUCCESS  = 'LOADING_USER_MESSAGES_SUCCESS';
export const LOADING_USER_MESSAGES  = 'LOADING_USER_MESSAGES';
export const LOADING_USER_MESSAGES_FAILED  = 'LOADING_USER_MESSAGES_FAILED';


export const LOADING_MYSHIPMENT_SUCCESS  = 'LOADING_MYSHIPMENT_SUCCESS';
export const LOADING_MYSHIPMENT  = 'LOADING_MYSHIPMENT';
export const LOADING_MYSHIPMENT_FAILED  = 'LOADING_MYSHIPMENT_FAILED';


export const EDITING_OFFER_SUCCESS  = 'EDITING_OFFER_SUCCESS';
export const EDITING_OFFER  = 'EDITING_OFFER';
export const EDITING_OFFER_FAILED  = 'EDITING_OFFER_FAILED';


export const REPORT_SUCCESS  = 'REPORT_SUCCESS';
export const ADDING_REPORT  = 'ADDING_REPORT';
export const REPORT_FAILED  = 'REPORT_FAILED';

export const LOADING_VEHICLE  = 'LOADING_VEHICLE';
export const LOADING_VEHICLE_SUCCESS  = 'LOADING_VEHICLE_SUCCESS';
export const LOADING_VEHICLE_FAILED  = 'LOADING_VEHICLE_FAILED';

export const SEND_LOCATION  = 'SEND_LOCATION';
export const SEND_LOCATION_SUCCESS  = 'SEND_LOCATION_SUCCESS';
export const SEND_LOCATION_FAILED  = 'SEND_LOCATION_FAILED';


export const EDITING_CART_FAILED  = 'EDITING_CART_FAILED';
export const EDITING_CART  = 'EDITING_CART';
export const EDITING_CART_SUCCESS  = 'EDITING_CART_SUCCESS';

export const ADDING_CART  = 'ADDING_CART';
export const ADDING_CART_SUCCESS  = 'ADDING_CART_SUCCESS';
export const ADDING_CART_FAILED  = 'ADDING_CART_FAILED';

export const LOADING_CART_SUCCESS  = 'LOADING_CART_SUCCESS';
export const LOADING_CART  = 'LOADING_CART';
export const LOADING_CART_FAILED  = 'LOADING_CART_FAILED';

export const DELETE_CART_SUCCESS  = 'DELETE_CART_SUCCESS';
export const DELETE_CART_FAILED  = 'DELETE_CART_FAILED';
export const DELETE_CART  = 'DELETE_CART';

export const LOADING_PRODUCTS_SUCCESS  = 'LOADING_PRODUCTS_SUCCESS';
export const LOADING_PRODUCTS_FAILED  = 'LOADING_PRODUCTS_FAILED';
export const LOADING_PRODUCTS  = 'LOADING_PRODUCTS';




